-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 18:03:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Base_datos_pos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Base_datos_pos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Base_datos_pos` DEFAULT CHARACTER SET utf8 ;
USE `Base_datos_pos` ;

-- -----------------------------------------------------
-- Table `Base_datos_pos`.`RolesUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_datos_pos`.`RolesUsuarios` (
  `idRolesUsuarios` INT NOT NULL,
  `idusuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolesUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Base_datos_pos`.`datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_datos_pos`.`datos` (
  `iddatos` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`iddatos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Base_datos_pos`.`Detalleformularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_datos_pos`.`Detalleformularios` (
  `idDetalleformularios` INT NOT NULL,
  `numformulario` VARCHAR(45) NOT NULL,
  `serieformulario` VARCHAR(45) NOT NULL,
  `codseguridad` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `dto_codigo` VARCHAR(45) NOT NULL,
  `datos_iddatos` INT NOT NULL,
  PRIMARY KEY (`idDetalleformularios`, `datos_iddatos`),
  INDEX `fk_Detalleformularios_datos1_idx` (`datos_iddatos` ASC) VISIBLE,
  CONSTRAINT `fk_Detalleformularios_datos1`
    FOREIGN KEY (`datos_iddatos`)
    REFERENCES `Base_datos_pos`.`datos` (`iddatos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Base_datos_pos`.`Contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_datos_pos`.`Contratos` (
  `idContratos` INT NOT NULL,
  `TipoContrato` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Detalleformularios_idDetalleformularios` INT NOT NULL,
  PRIMARY KEY (`idContratos`, `Detalleformularios_idDetalleformularios`),
  INDEX `fk_Contratos_Detalleformularios1_idx` (`Detalleformularios_idDetalleformularios` ASC) VISIBLE,
  CONSTRAINT `fk_Contratos_Detalleformularios1`
    FOREIGN KEY (`Detalleformularios_idDetalleformularios`)
    REFERENCES `Base_datos_pos`.`Detalleformularios` (`idDetalleformularios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Base_datos_pos`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_datos_pos`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `correo` VARCHAR(300) NOT NULL,
  `celular` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `RolesUsuarios_idRolesUsuarios` INT NOT NULL,
  `Contratos_idContratos` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `RolesUsuarios_idRolesUsuarios`, `Contratos_idContratos`),
  INDEX `fk_Usuarios_RolesUsuarios_idx` (`RolesUsuarios_idRolesUsuarios` ASC) VISIBLE,
  INDEX `fk_Usuarios_Contratos1_idx` (`Contratos_idContratos` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_RolesUsuarios`
    FOREIGN KEY (`RolesUsuarios_idRolesUsuarios`)
    REFERENCES `Base_datos_pos`.`RolesUsuarios` (`idRolesUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Contratos1`
    FOREIGN KEY (`Contratos_idContratos`)
    REFERENCES `Base_datos_pos`.`Contratos` (`idContratos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Base_datos_pos`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_datos_pos`.`Roles` (
  `idRoles` INT NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `DescripcionRol` VARCHAR(45) NOT NULL,
  `RolesUsuarios_idRolesUsuarios` INT NOT NULL,
  PRIMARY KEY (`idRoles`),
  INDEX `fk_Roles_RolesUsuarios1_idx` (`RolesUsuarios_idRolesUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Roles_RolesUsuarios1`
    FOREIGN KEY (`RolesUsuarios_idRolesUsuarios`)
    REFERENCES `Base_datos_pos`.`RolesUsuarios` (`idRolesUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
